global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'system-monitoring'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']  # Host network port
    scrape_interval: 15s

  # PostgreSQL Exporter - NOW CAN ACCESS ANY IP/CONTAINER
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']  # Via host network
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Node Exporter - Via host network
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']  # Via host network
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: [] 